server:
  port: 8080
debug: true
spring:
  application:
    name: DemoSpringBootKafka
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  kafka:
    bootstrap-servers: ${kafka.boostrap-servers}
    consumer:
      group-id: ${kafka.consumer.group-id}
kafka:
  topics:
    demo:
      input: topic.demo.input
      output: topic.demo.output